# Generated by Django 6.0.8 on 2026-09-30 00:56

import django.db.models.deletion
import uuid
import wger.manager.models.routine_recovery
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_workoutlog_cardio_station'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='replaced_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manager.routine'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='routine',
            field=models.ForeignKey(null=True, on_delete=wger.manager.models.routine_recovery.protect_history, to='manager.routine', verbose_name='Workout'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='slot_entry',
            field=models.ForeignKey(null=True, on_delete=wger.manager.models.routine_recovery.protect_history, to='manager.slotentry'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='day',
            field=models.ForeignKey(null=True, on_delete=wger.manager.models.routine_recovery.protect_history, to='manager.day'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='routine',
            field=models.ForeignKey(null=True, on_delete=wger.manager.models.routine_recovery.protect_history, related_name='sessions', to='manager.routine'),
        ),
        migrations.CreateModel(
            name='RoutineRecovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('trash', 'trash'), ('edit', 'edit'), ('rebuild', 'rebuild'), ('restore', 'restore')], max_length=10)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('restored_at', models.DateTimeField(null=True)),
                ('snapshot', models.JSONField()),
                ('revision_after', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=100, null=True)),
                ('request_hash', models.CharField(max_length=64, null=True)),
                ('receipt', models.JSONField(null=True)),
                ('replacement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='manager.routine')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='manager.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'expires_at'], name='routine_recovery_owner_expiry')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('user', 'idempotency_key'), name='routine_recovery_idempotency')],
            },
        ),
    ]
