# Generated by Django 6.0.8 on 2026-09-30 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_routine_recovery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='time_unknown',
            field=models.BooleanField(default=False, editable=False, verbose_name='Time unknown'),
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.CheckConstraint(condition=models.Q(('time_unknown', False), ('datetime_end__isnull', False), _connector='OR'), name='session_time_unknown_has_end'),
        ),
    ]
