# Generated by Django 6.0.8 on 2026-09-30 03:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0034_workoutsession_time_unknown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutinePreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('external_version', models.CharField(max_length=100)),
                ('request_hash', models.CharField(max_length=64)),
                ('plan_hash', models.CharField(db_index=True, max_length=64)),
                ('canonical_proposal', models.JSONField()),
                ('schedule', models.JSONField()),
                ('exercise_names', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_previews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'idempotency_key'), name='routine_preview_unique_idempotency_key')],
            },
        ),
    ]
