# Generated by Django 6.0.8 on 2026-09-29 10:56

import django.db.models.deletion
import wger.utils.uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnduranceEntry',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=wger.utils.uuid.uuid7, primary_key=True, serialize=False
                    ),
                ),
                (
                    'kind',
                    models.CharField(
                        choices=[('planned', 'planned'), ('completed', 'completed')], max_length=9
                    ),
                ),
                ('intervals_id', models.CharField(max_length=32)),
                ('sport', models.CharField(max_length=40, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('start_local', models.CharField(max_length=32)),
                ('local_date', models.DateField(db_index=True)),
                ('timezone', models.CharField(max_length=64, null=True)),
                ('moving_time_s', models.IntegerField(null=True)),
                ('elapsed_time_s', models.IntegerField(null=True)),
                ('distance_m', models.FloatField(null=True)),
                ('training_load', models.IntegerField(null=True)),
                ('power_load', models.IntegerField(null=True)),
                ('hr_load', models.IntegerField(null=True)),
                ('pace_load', models.IntegerField(null=True)),
                ('hr_load_type', models.CharField(max_length=16, null=True)),
                ('pace_load_type', models.CharField(max_length=16, null=True)),
                ('intensity', models.FloatField(null=True)),
                ('avg_hr', models.IntegerField(null=True)),
                ('max_hr', models.IntegerField(null=True)),
                ('rpe', models.IntegerField(null=True)),
                ('feel', models.IntegerField(null=True)),
                ('load_target', models.IntegerField(null=True)),
                ('time_target', models.IntegerField(null=True)),
                ('paired_event_id', models.IntegerField(null=True)),
                ('activity_source', models.CharField(max_length=32, null=True)),
                (
                    'upstream_state',
                    models.CharField(
                        choices=[('present', 'present'), ('missing', 'missing')],
                        default='present',
                        max_length=7,
                    ),
                ),
                ('fetched_at', models.DateTimeField()),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'ordering': ['local_date', 'start_local'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('user', 'kind', 'intervals_id'), name='intervals_endurance_identity'
                    )
                ],
            },
        ),
    ]
