# Generated by Django 6.0.8 on 2026-09-29 20:35

import django.db.models.deletion
import wger.utils.uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('intervals', '0001_initial'),
        ('manager', '0032_workoutlog_cardio_station'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalsEventLink',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=wger.utils.uuid.uuid7, primary_key=True, serialize=False
                    ),
                ),
                ('external_id', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('intervals_event_id', models.BigIntegerField(null=True)),
                ('pushed_hash', models.CharField(max_length=64)),
                (
                    'state',
                    models.CharField(
                        choices=[('active', 'active'), ('deleted', 'deleted')],
                        default='active',
                        max_length=7,
                    ),
                ),
                ('pushed_at', models.DateTimeField()),
                (
                    'day',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.day'
                    ),
                ),
                (
                    'routine',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='manager.routine',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'ordering': ['date', 'external_id'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('user', 'external_id'), name='intervals_event_link_identity'
                    )
                ],
            },
        ),
    ]
