# Generated by Django 6.0.8 on 2026-09-30

import django.db.models.deletion
import wger.utils.uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('intervals', '0002_intervalseventlink'),
        ('manager', '0034_workoutsession_time_unknown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalsActivityLink',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=wger.utils.uuid.uuid7, primary_key=True, serialize=False
                    ),
                ),
                ('external_id', models.CharField(max_length=64)),
                ('intervals_activity_id', models.CharField(max_length=32, null=True)),
                ('pushed_hash', models.CharField(max_length=64)),
                ('pushed_at', models.DateTimeField()),
                (
                    'session',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='manager.workoutsession',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('user', 'external_id'), name='intervals_activity_link_identity'
                    ),
                ],
            },
        ),
    ]
