# Generated by Django 6.0.8 on 2026-09-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('intervals', '0002_intervalseventlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervalseventlink',
            name='removal',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='intervalseventlink',
            name='state',
            field=models.CharField(
                choices=[
                    ('active', 'active'),
                    ('deleted', 'deleted'),
                    ('removing', 'removing'),
                    ('removed', 'removed'),
                ],
                default='active',
                max_length=8,
            ),
        ),
    ]
